package com.ztesoft.zsmart.bss.sfa.lead.dao.mysqlimpl;

/**
 * <p>Title:ZSMART </p>
 *
 * <p>Description: IndustryDAO </p>
 *
 * <p>Copyright: Copyright (c) 2008</p>
 *
 * <p>Company:ztesoft </p>
 *
 * <p>Created Date:2011-9-28 13:34:50 </p>
 *
 * @author:   Auto Generated by CodeSmith 3.0 
 * @version R11
 */

import com.ztesoft.zsmart.bss.sfa.lead.dao.IIndustryExDAO;
import com.ztesoft.zsmart.bss.sfa.lead.model.IndustryDto;
import com.ztesoft.zsmart.core.exception.BaseAppException;
import com.ztesoft.zsmart.core.jdbc.BaseDAO;
import com.ztesoft.zsmart.core.jdbc.ParamArray;
import com.ztesoft.zsmart.core.jdbc.rowset.RowSetMapper;
import com.ztesoft.zsmart.core.jdbc.rowset.RowSetOperator;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * 
 * <Description> <br> 
 *  
 * @author <br>
 * @version V8<br>
 * @taskId <br>
 * @CreateDate 2012-9-4 <br>
 * @since V8<br>
 * @see com.ztesoft.zsmart.bss.sfa.lead.dao.abstractimpl <br>
 */
public class IndustryExDAOMysql extends BaseDAO implements IIndustryExDAO {
    /**
     * 构造函数
     */
    public IndustryExDAOMysql() {
    }

    /**
     * 
     * Description:查询 <br> 
     *  
     * @author <br>
     * @taskId <br>
     * @param industryCode String
     * @param spId String
     * @return IndustryDto
     * @throws BaseAppException <br>
     */
    public IndustryDto selectIndustry(String industryCode, Long spId) throws BaseAppException {
        String sqlStr = "SELECT \r\n" + " INDUSTRY_ID,INDUSTRY_NAME,SP_ID \r\n" + " FROM  SFA_INDUSTRY \r\n"
            + " WHERE INDUSTRY_CODE=? AND SP_ID=?";

        ParamArray pa = new ParamArray();
        pa.set("INDUSTRY_CODE", industryCode);
        pa.set("SP_ID", spId);

        return (IndustryDto) query(sqlStr, pa, null, new RowSetMapper() {
            public Object mapRows(RowSetOperator op, ResultSet rs, int colNum, Object para) throws SQLException,
                BaseAppException {
                IndustryDto dto = null;
                if (rs.next()) {
                    int dbloop = 1;
                    dto = new IndustryDto();
                    dto.setIndustryId(op.getLong(rs, dbloop++));
                    dto.setIndustryName(op.getString(rs, dbloop++));
                    dto.setSpId(op.getLong(rs, dbloop++));
                }
                return dto;
            }
        });
    }
    
    /**
     * 
     * Description: <br> 
     *  
     * @author song.chenghao<br>
     * @taskId <br>
     * @param industryId <br>
     * @return <br>
     * @throws BaseAppException <br>
     */
    public IndustryDto selectIndustryByPK(Long industryId) throws BaseAppException {
        String sqlStr = "SELECT \r\n" + " INDUSTRY_ID,INDUSTRY_NAME,SP_ID \r\n" + " FROM  SFA_INDUSTRY \r\n"
            + " WHERE INDUSTRY_ID = ?";

        ParamArray pa = new ParamArray();
        pa.set("INDUSTRY_ID", industryId);

        return (IndustryDto) query(sqlStr, pa, null, new RowSetMapper() {
            public Object mapRows(RowSetOperator op, ResultSet rs, int colNum, Object para) throws SQLException,
                BaseAppException {
                IndustryDto dto = null;
                if (rs.next()) {
                    int dbloop = 1;
                    dto = new IndustryDto();
                    dto.setIndustryId(op.getLong(rs, dbloop++));
                    dto.setIndustryName(op.getString(rs, dbloop++));
                    dto.setSpId(op.getLong(rs, dbloop++));
                }
                return dto;
            }
        });
    }

}
